//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_master_pro__mvc_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edu_details
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public string qualification { get; set; }
        public Nullable<int> marks { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public Nullable<int> sts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lum { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
