//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin_master_pro__mvc_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.edu_details = new HashSet<edu_details>();
        }
    
        public System.Guid ID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string contactnumber { get; set; }
        public string companyname { get; set; }
        public Nullable<System.DateTime> dateofjoining { get; set; }
        public string rco { get; set; }
        public Nullable<System.DateTime> rcm { get; set; }
        public Nullable<int> sts { get; set; }
        public string luo { get; set; }
        public Nullable<System.DateTime> lum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<edu_details> edu_details { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
    }
}
